[package]
name = "aleksandr-vinokurov-cv"
version = "2023.10.0"
edition = "2021"

include = ["src/**/*.rs", "src/sample.tex", "Cargo.toml"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

